# version: '3.8'
x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  env_file:
    - .env
  environment:
    DB_HOST: postgres
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./ingestion:/opt/airflow/ingestion
    - ./dbt:/opt/airflow/dbt
    - ./spark:/opt/airflow/spark
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
  airflow-init:
    <<: *airflow-common
    restart: on-failure
    entrypoint: /bin/bash
    command: 
      - -c 
      - |
        airflow db migrate && 
        airflow users create \
          --username admin \
          --password admin \
          --firstname Patrick \
          --lastname Storm \
          --role Admin \
          --email patrick.t.storm.dev@gmail.com
  airflow-webserver:
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always
  airflow-scheduler:
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    <<: *airflow-common
    command: scheduler
    restart: always
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/airflow
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: always

volumes:
  postgres_data: